[tool.poetry]
name = "reddit-data-extractor"
version = "0.1.0"
description = ""
authors = ["stnorbi <streling.norbert@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
